export const INITIAL_STATE = "INITIAL_STATE";

export const LOGIN_LOADING = "LOGIN_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_LOADING = "REGISTER_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_ERROR = "REGISTER_ERROR";

export const ADD_SOURCE_LOADING = "ADD_SOURCE_LOADING";

export const ADD_SOURCE_SUCCESS = "ADD_SOURCE_SUCCESS";

export const ADD_SOURCE_ERROR = "ADD_SOURCE_ERROR";

export const EDIT_SOURCE_LOADING = "EDIT_SOURCE_LOADING";

export const EDIT_SOURCE_SUCCESS = "EDIT_SOURCE_SUCCESS";

export const EDIT_SOURCE_ERROR = "EDIT_SOURCE_ERROR";

export const DELETE_SOURCE_LOADING = "DELETE_SOURCE_LOADING";

export const DELETE_SOURCE_SUCCESS = "DELETE_SOURCE_SUCCESS";

export const DELETE_SOURCE_ERROR = "DELETE_SOURCE_ERROR";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_USER_ERROR = "GET_USER_ERROR";

export const LOGOUT = "LOGOUT";

export const RESET_REGISTER_STATUS = "RESET_REGISTER_STATUS";

export const RESET_LOGIN_STATUS = "RESET_LOGIN_STATUS";

export const RESET_ADD_SOURCE_STATUS = "RESET_ADD_SOURCE_STATUS";

export const RESET_EDIT_SOURCE_STATUS = "RESET_EDIT_SOURCE_STATUS";

export const RESET_DELETE_SOURCE_STATUS = "RESET_DELETE_SOURCE_STATUS";
